### ISSUE TITLE
Exception at shutdown

### ISSUE THREAD

**Issue by akara** [paypal/squbs#294]
Not a serious issue, but we should take care of it rather easily:

```
[error] Exception in thread "shutdownHook1" java.util.NoSuchElementException
[error]     at scala.collection.concurrent.TrieMap.apply(TrieMap.scala:837)
[error]     at org.squbs.unicomplex.Shutdown$.shutdown(Bootstrap.scala:54)
[error]     at org.squbs.unicomplex.Bootstrap$$anonfun$1.apply$mcV$sp(Bootstrap.scala:42)
[error]     at scala.sys.ShutdownHookThread$$anon$1.run(ShutdownHookThread.scala:34)
```

**Comment by akara** [comment]
Fixed by #297 and #298
