### ISSUE TITLE
Codacy report upload is broken

### ISSUE THREAD

**Issue by anilgursel** [paypal/squbs#399]
PR builds are failing with the following error:

```
java.lang.RuntimeException: Failed to upload data. Reason: Not Found
	at scala.sys.package$.error(package.scala:27)
	at com.codacy.CodacyCoveragePlugin$$anonfun$1.apply(CodacyCoveragePlugin.scala:60)
	at com.codacy.CodacyCoveragePlugin$$anonfun$1.apply(CodacyCoveragePlugin.scala:45)
	at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1$$anonfun$apply$2.apply(FileHelper.scala:19)
	at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1$$anonfun$apply$2.apply(FileHelper.scala:17)
	at scala.Option.map(Option.scala:145)
	at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1.apply(FileHelper.scala:17)
	at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1.apply(FileHelper.scala:16)
	at com.codacy.api.helpers.FileHelper$$anonfun$withCommit$2.apply(FileHelper.scala:32)
	at com.codacy.api.helpers.FileHelper$$anonfun$withCommit$2.apply(FileHelper.scala:31)
	at scala.Option.map(Option.scala:145)
	at com.codacy.api.helpers.FileHelper$.withCommit(FileHelper.scala:31)
	at com.codacy.api.helpers.FileHelper$.withTokenAndCommit(FileHelper.scala:16)
	at com.codacy.CodacyCoveragePlugin$.com$codacy$CodacyCoveragePlugin$$codacyCoverageCommand(CodacyCoveragePlugin.scala:45)
	at com.codacy.CodacyCoveragePlugin$AutoImport$$anonfun$baseSettings$2.apply(CodacyCoveragePlugin.scala:22)
	at com.codacy.CodacyCoveragePlugin$AutoImport$$anonfun$baseSettings$2.apply(CodacyCoveragePlugin.scala:21)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (squbs/*:codacyCoverage) Failed to upload data. Reason: Not Found
[error] Total time: 5 s, completed Feb 9, 2017 2:14:37 AM
The command "sbt codacyCoverage" exited with 1.
```

**Comment by anilgursel** [comment]
Need to upgrade the plugins and also need to check the tokens: https://gitter.im/paypal/squbs?at=589bdbacf045df0a22243602.
