### ISSUE TITLE
Fix build stability issues - builds must not sporadically fail.

### ISSUE THREAD

**Issue by akara** [paypal/squbs#85]

**Comment by akara** [comment]
New build failure popping up:

[info] PipelineManagerSpec:
[info] PipelineManager getProcessor
[info] - should work *** FAILED ***
[info]   14 was not equal to 4 (PipelineManagerSpec.scala:123)
[info] PipelineManager getPipelineSetting
06:28:23.326 [pool-1-thread-1-ScalaTest-running-PipelineManagerSpec] ERROR org.squbs.pipeline.PipelineManager - Can't instantiate squbs.proxy with name of pipe3 and factory class name of org.squbs.pipeline.TestResolver3
java.lang.ClassNotFoundException: org.squbs.pipeline.TestResolver3
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_31]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_31]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_31]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_31]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_31]
	at java.lang.Class.forName(Class.java:260) ~[na:1.8.0_31]
	at org.squbs.pipeline.PipelineManager.get(PipelineManager.scala:58) [classes/:na]
	at org.squbs.pipeline.PipelineManager.getPipelineSetting(PipelineManager.scala:44) [classes/:na]
	at org.squbs.pipeline.PipelineManagerSpec$$anonfun$2$$anonfun$apply$mcV$sp$6.apply(PipelineManagerSpec.scala:160) [test-classes/:na]
	at org.squbs.pipeline.PipelineManagerSpec$$anonfun$2$$anonfun$apply$mcV$sp$6.apply(PipelineManagerSpec.scala:160) [test-classes/:na]
	at org.scalatest.Assertions$.checkExpectedException(Assertions.scala:1565) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.words.ResultOfTheTypeInvocation.thrownBy(ResultOfTheTypeInvocation.scala:38) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec$$anonfun$2.apply$mcV$sp(PipelineManagerSpec.scala:159) [test-classes/:na]
	at org.squbs.pipeline.PipelineManagerSpec$$anonfun$2.apply(PipelineManagerSpec.scala:140) [test-classes/:na]
	at org.squbs.pipeline.PipelineManagerSpec$$anonfun$2.apply(PipelineManagerSpec.scala:140) [test-classes/:na]
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.Transformer.apply(Transformer.scala:22) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.Transformer.apply(Transformer.scala:20) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec.withFixture(PipelineManagerSpec.scala:28) [test-classes/:na]
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1644) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1656) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec.runTest(PipelineManagerSpec.scala:28) [test-classes/:na]
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [scalatest_2.11-2.2.1.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:381) [scala-library-2.11.7.jar:na]
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [scalatest_2.11-2.2.1.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:381) [scala-library-2.11.7.jar:na]
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1714) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec.runTests(PipelineManagerSpec.scala:28) [test-classes/:na]
	at org.scalatest.Suite$class.run(Suite.scala:1424) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec.org$scalatest$FlatSpecLike$$super$run(PipelineManagerSpec.scala:28) [test-classes/:na]
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1760) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec.run(PipelineManagerSpec.scala:28) [test-classes/:na]
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:462) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:671) [scalatest_2.11-2.2.1.jar:na]
	at sbt.ForkMain$Run$2.call(ForkMain.java:294) [test-agent-0.13.7.jar:0.13.7]
	at sbt.ForkMain$Run$2.call(ForkMain.java:284) [test-agent-0.13.7.jar:0.13.7]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
06:28:23.334 [pool-1-thread-1-ScalaTest-running-PipelineManagerSpec] ERROR org.squbs.pipeline.PipelineManager - Can't instantiate squbs.proxy with name of pipe4 and factory class name of org.squbs.pipeline.TestResolver4
java.lang.IllegalArgumentException: Unsupported processor factory: org.squbs.pipeline.TestResolver4
	at org.squbs.pipeline.PipelineManager.get(PipelineManager.scala:65) [classes/:na]
	at org.squbs.pipeline.PipelineManager.getPipelineSetting(PipelineManager.scala:44) [classes/:na]
	at org.squbs.pipeline.PipelineManagerSpec$$anonfun$2$$anonfun$apply$mcV$sp$7.apply(PipelineManagerSpec.scala:165) [test-classes/:na]
	at org.squbs.pipeline.PipelineManagerSpec$$anonfun$2$$anonfun$apply$mcV$sp$7.apply(PipelineManagerSpec.scala:165) [test-classes/:na]
	at org.scalatest.Assertions$.checkExpectedException(Assertions.scala:1565) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.words.ResultOfTheTypeInvocation.thrownBy(ResultOfTheTypeInvocation.scala:38) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec$$anonfun$2.apply$mcV$sp(PipelineManagerSpec.scala:164) [test-classes/:na]
	at org.squbs.pipeline.PipelineManagerSpec$$anonfun$2.apply(PipelineManagerSpec.scala:140) [test-classes/:na]
	at org.squbs.pipeline.PipelineManagerSpec$$anonfun$2.apply(PipelineManagerSpec.scala:140) [test-classes/:na]
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.Transformer.apply(Transformer.scala:22) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.Transformer.apply(Transformer.scala:20) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec.withFixture(PipelineManagerSpec.scala:28) [test-classes/:na]
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1644) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1656) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec.runTest(PipelineManagerSpec.scala:28) [test-classes/:na]
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [scalatest_2.11-2.2.1.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:381) [scala-library-2.11.7.jar:na]
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [scalatest_2.11-2.2.1.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:381) [scala-library-2.11.7.jar:na]
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1714) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec.runTests(PipelineManagerSpec.scala:28) [test-classes/:na]
	at org.scalatest.Suite$class.run(Suite.scala:1424) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec.org$scalatest$FlatSpecLike$$super$run(PipelineManagerSpec.scala:28) [test-classes/:na]
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1760) [scalatest_2.11-2.2.1.jar:na]
	at org.squbs.pipeline.PipelineManagerSpec.run(PipelineManagerSpec.scala:28) [test-classes/:na]
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:462) [scalatest_2.11-2.2.1.jar:na]
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:671) [scalatest_2.11-2.2.1.jar:na]
	at sbt.ForkMain$Run$2.call(ForkMain.java:294) [test-agent-0.13.7.jar:0.13.7]
	at sbt.ForkMain$Run$2.call(ForkMain.java:284) [test-agent-0.13.7.jar:0.13.7]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

**Comment by akara** [comment]
One more issue. Just happened once:

[info] - must 6.1) getBean after actor has been stop *** FAILED ***
[info]   None was not defined (ActorMonitorSpec.scala:287)
